config/routes.rb
Ape::Application.routes.draw do
  resources :projects

  # Comments
  match '/projects/:project_id/:type/comments/:id/edit(.:format)' => 'comments#edit', :as => 'edit_index_comment', :via => 'get'
  match '/projects/:project_id/:type/comments(.:format)' => 'comments#create', :as => 'index_comments', :via => 'post'
  match '/projects/:project_id/:type/comments/:id(.:format)' => 'comments#update', :as => 'index_comment', :via => 'put'
  match '/projects/:project_id/:type/comments/:id(.:format)' => 'comments#destroy', :as => 'index_comment', :via => 'delete'

  match '/projects/:project_id/:type/*type_id/comments/:id/edit(.:format)' => 'comments#edit', :as => 'edit_comment', :via => 'get'
  match '/projects/:project_id/:type/*type_id/comments(.:format)' => 'comments#create', :as => 'comments', :via => 'post'
  match '/projects/:project_id/:type/*type_id/comments/:id(.:format)' => 'comments#update', :as => 'comment', :via => 'put'
  match '/projects/:project_id/:type/*type_id/comments/:id(.:format)' => 'comments#destroy', :as => 'comment', :via => 'delete'

  # Wiki index
  match '/projects/:project_id/wiki/structure(.:format)' => 'wiki#structure', :as => 'wiki_structure', :via => 'get'
  match '/projects/:project_id/wiki(.:format)' => 'wiki#index', :as => 'wiki_index', :via => 'get'
  match '/projects/:project_id/wiki/edit(.:format)' => 'wiki#edit', :as => 'edit_wiki_index', :via => 'get'
  match '/projects/:project_id/wiki(.:format)' => 'wiki#update', :as => 'wiki_index', :via => 'put'
  match '/projects/:project_id/wiki/new(.:format)' => 'wiki#new', :as => 'new_wiki_index_page', :via => 'get'
  match '/projects/:project_id/wiki(.:format)' => 'wiki#create', :as => 'wiki_index_page', :via => 'post'
  match '/projects/:project_id/wiki/pages(.:format)' => 'wiki#pages', :as => 'wiki_index_pages', :via => 'get'
  match '/projects/:project_id/wiki/revisions(.:format)' => 'wiki#revisions', :as => 'wiki_index_revisions', :via => 'get'

  # Wiki pages
  match '/projects/:project_id/wiki/*id/pages(.:format)' => 'wiki#pages', :as => 'wiki_pages', :via => 'get'
  match '/projects/:project_id/wiki/*id/revisions(.:format)' => 'wiki#revisions', :as => 'wiki_page_revisions', :via => 'get'
  match '/projects/:project_id/wiki/*id/new(.:format)' => 'wiki#new', :as => 'new_wiki_page', :via => 'get'
  match '/projects/:project_id/wiki/*id/edit(.:format)' => 'wiki#edit', :as => 'edit_wiki_page', :via => 'get'
  match '/projects/:project_id/wiki/*id(.:format)' => 'wiki#show', :as => 'wiki_page', :via => 'get'
  match '/projects/:project_id/wiki/*id(.:format)' => 'wiki#create', :as => 'wiki_page', :via => 'post'
  match '/projects/:project_id/wiki/*id(.:format)' => 'wiki#update', :as => 'wiki_page', :via => 'put'
  match '/projects/:project_id/wiki/*id(.:format)' => 'wiki#destroy', :as => 'wiki_page', :via => 'delete'

  # Tickets
  match '/projects/:project_id/tickets(.:format)' => 'tickets#index', :as => 'tickets', :via => 'get'
  match '/projects/:project_id/tickets(.:format)' => 'tickets#create', :as => 'tickets', :via => 'post'
  match '/projects/:project_id/tickets/*id(.:format)' => 'tickets#create', :as => 'create_sub_ticket', :via => 'post'
  match '/projects/:project_id/tickets/new(.:format)' => 'tickets#new', :as => 'new_ticket', :via => 'get'
  match '/projects/:project_id/tickets/*id/new(.:format)' => 'tickets#new', :as => 'new_sub_ticket', :via => 'get'
  match '/projects/:project_id/tickets/*id/edit(.:format)' => 'tickets#edit', :as => 'edit_ticket', :via => 'get'
  match '/projects/:project_id/tickets/*id(.:format)' => 'tickets#show', :as => 'ticket', :via => 'get'
  match '/projects/:project_id/tickets/*id(.:format)' => 'tickets#update', :as => 'ticket', :via => 'put'
  match '/projects/:project_id/tickets/*id(.:format)' => 'tickets#destroy', :as => 'ticket', :via => 'delete'

  root :to => 'projects#index'
end

app/models/wiki.rb
class Wiki < Versionable
  def initialize(hash)
    super hash.merge(:type_identifier => 'wiki')
  end

  def self.type_identifier
    'wiki'
  end

  def self.all(hash)
    super hash.merge(:type_identifier => self.type_identifier)
  end

  def self.find(hash)
    super hash.merge(:type_identifier => self.type_identifier)
  end

  def index?
    @id.empty?
  end
end

app/controllers/wiki_controller.rb
class WikiController < ApplicationController
  before_filter :get_project

  def index
    @wiki = Wiki.find({:project => @project, :id => ''})
    @comments = Comment.all({:project => @project, :type => 'wiki', :type_id => ''})
  end

  def show
    @wiki = Wiki.find({:project => @project, :id => params[:id]})
    if @wiki.contents.empty?
      parent = @wiki.parent
      if (parent.nil?)
        render_404
      else
        dirs = File.split @wiki.id
        new_page = dirs[1]
        if parent.index?
          redirect_to new_wiki_index_page_url :name => new_page
        else
          redirect_to new_wiki_page_url :id => parent.id, :name => new_page
        end
      end
    else
      @comments = Comment.all({:project => @project, :type => 'wiki', :type_id => @wiki.id})
    end
  end

  def new
    @wiki = Wiki.new({:project => @project, :id => File.join(params[:id].to_s, '')})
  end

  def create
    wiki = Wiki.new({:project => @project, :id => File.join(params[:id].to_s, params[:name]), :contents => params[:content]})

    message = params[:commit_message]
    if message.empty?
      message = 'Add page: ' + params[:name]
    end

    wiki.save! message

    if (params[:commit] == I18n.t(:save_and_continue))
      redirect_to edit_wiki_page_url :id => wiki.id
    else
      redirect_to wiki_page_url :id => wiki.id
    end
  end

  def edit
    @wiki = Wiki.find({:project => @project, :id => params[:id], :revision => params[:revision]})
    @contents = @wiki.contents
  end

  def update
    wiki = Wiki.find({:project => @project, :id => params[:id]})

    message = params[:commit_message]
    if message.empty?
      message = 'Update page: ' + wiki.id
    end

    wiki.contents = params[:content]

    wiki.save! message

    if (params[:commit] == I18n.t(:save_and_continue))
      redirect_to((wiki.index? ? edit_wiki_index_url : edit_wiki_page_url(:id => wiki.id)))
    else
      redirect_to((wiki.index? ? wiki_index_url : wiki_page_url(:id => wiki.id)))
    end
  end

  def destroy
    wiki = Wiki.find({:project => @project, :id => params[:id]})

    message = params[:commit_message].to_s
    if message.empty?
      message = 'Delete page: ' + wiki.id
    end

    parent = wiki.parent

    wiki.destroy! message

    if (parent.nil?)
      redirect_to wiki_index_url
    else
      redirect_to((parent.index? ? wiki_index_url : wiki_page_url(:id => parent.id)))
    end
  end

  def pages
    @wiki = Wiki.find({:project => @project, :id => params[:id]})
    @pages = @wiki.children
  end

  def revisions
    @wiki = Wiki.find({:project => @project, :id => params[:id]})
    @revisions = @wiki.revisions
  end

  def structure
    @pages = Wiki.all({:project => @project})
  end

  private
    def get_project
      @project = Project.find_by_slug params[:project_id]
    end
end

app/helpers/wiki_helper.rb
module WikiHelper
end

app/views/wiki/_comments.html.erb
<% unless @comments.empty? %>
  <h2><%= t(:comments) %></h2>
  <ul class="no-list">
  <% @comments.each do |comment| %>
    <% if @wiki.index? %>
      <% edit_path = edit_index_comment_path(:project_id => params[:project_id], :type => :wiki, :id => comment.id) %>
      <% delete_path = index_comment_path(:project_id => params[:project_id], :type => :wiki, :id => comment.id) %>
    <% else %>
      <% edit_url = edit_comment_path(:project_id => params[:project_id], :type_id => params[:id].to_s, :type => :wiki, :id => comment.id) %>
      <% delete_path = comment_path(:project_id => params[:project_id], :type_id => params[:id].to_s, :type => :wiki, :id => comment.id) %>
    <% end -%>
    <li class="<%= cycle('even', 'odd') %>">
      <div class="span-4">
        <strong><%= mail_to comment.email, comment.name %></strong><br />
        <%= l(comment.date, :format => :short) %><br />
        <%= gravatar_for comment %>
      </div>
      <div class="span-19 last">
        <div class="right">
          <%= link_to t(:edit), edit_path %>
          <%= button_to t(:delete), delete_path, :method => :delete, :confirm => t(:are_you_sure) %>
        </div>
        <%= rewrite_wiki_links comment %>
      </div>
      <div class="breaker"></div>
    </li>
  <% end -%>
  </ul>
<% end -%>

app/views/wiki/_contents.html.erb
<%= render 'menu', :no_edit => false %>

<%= rewrite_wiki_links @wiki %>

<hr />

<strong class="right"><%= t(:updated_on_by, :date => l(@wiki.date, :format => :long), :name => @wiki.name) %></strong>

<%= render :partial => 'comments' %>

<h2><%= t(:new_comment) %></h2>

<% if @wiki.index? %>
  <% url = index_comments_url(:project_id => params[:project_id], :type => :wiki) %>
<% else %>
  <% url = comments_url(:project_id => params[:project_id], :type_id => params[:id].to_s, :type => :wiki) %>
<% end -%>

<%= form_tag url do |f| %>
  <ul class="no-list">
    <li>
      <%= label_tag :comment %><br />
      <%= text_area_tag :comment %>
    </li>
    <li>
      <%= submit_tag t(:new_comment) %>
    </li>
  </ul>
<% end %>

app/views/wiki/_menu.html.erb
<%= link_to t(:home), wiki_index_url %> |
<%= link_to t(:structure), wiki_structure_url %>

<% unless (@wiki.nil?) %>
  <% if (@wiki.index?) %>
    <% edit_url = edit_wiki_index_url %>
    <% pages_url = wiki_index_pages_url %>
    <% revisions_url = wiki_index_revisions_url %>
  <% else %>
    <% edit_url = edit_wiki_page_url %>
    <% pages_url = wiki_pages_url %>
    <% revisions_url = wiki_page_revisions_url %>
  <% end %>

  <% unless @wiki.index? %>
    <% if (@wiki.parent.index?) %>
      | <%= link_to t(:parent), wiki_index_url(@project) %>
    <% else %>
      | <%= link_to t(:parent), wiki_page_url(@project, :id => @wiki.parent.id) %>
    <% end %>
  <% end %>

  | <%= link_to t(:pages) + '(' + @wiki.children.count.to_s + ')', pages_url %>
  | <%= link_to t(:revisions) + '(' + @wiki.revisions.count.to_s + ')', revisions_url %>

  <% unless no_edit %>
     | <%= link_to t(:edit), edit_url %>
  <% end %>

  <% unless @wiki.index? %>
    <div class="right">
      <%= button_to t(:delete), wiki_page_path(@project), :method => :delete, :confirm => t(:are_you_sure) %>
    </div>
  <% end -%>
<% else %>

<% end %>
<hr />

app/views/wiki/edit.html.erb
<h1><%= t :edit_wiki_page %></h1>

<% if (@wiki.index?) %>
  <% url = wiki_index_url(@project) %>
<% else %>
  <% url = wiki_page_url(@project) %>
<% end %>

<%= form_tag url, {:method => :put} do |f| %>
  <div id="wiki-form">
    <ul>
      <li>
        <%= label_tag :content %><br />
        <%= text_area_tag :content, @contents %>
      </li>
      <li>
        <%= label_tag :commit_message %><br />
        <%= text_field_tag :commit_message %>
      </li>
      <li>
        <%= submit_tag t(:save) %> | <%= submit_tag t(:save_and_continue) %> | <%= link_to t(:cancel), url %>
      </li>
    </ul>
  </div>
<% end %>

app/views/wiki/index.html.erb
<h1><%= @project.name %></h1>

<%= render 'contents' %>

app/views/wiki/new.html.erb
<h1><%= t :new_wiki_page %></h1>

<% if (@wiki.index?) %>
  <% url = wiki_index_page_url(@project) %>
<% else %>
  <% url = wiki_page_url(@project) %>
<% end %>

<%= form_tag url do |f| %>
  <div id="wiki-form">
    <ul>
      <li>
        <%= label_tag :name %><br />
        <%= text_field_tag :name, params[:name].to_s %>
      </li>
      <li>
        <%= label_tag :content %><br />
        <%= text_area_tag :content %>
      </li>
      <li>
        <%= label_tag :commit_message %><br />
        <%= text_field_tag :commit_message %>
      </li>
      <li>
        <%= submit_tag t(:save) %> | <%= submit_tag t(:save_and_continue) %> | <%= link_to t(:cancel), url %>
      </li>
    </ul>
  </div>
<% end %>

app/views/wiki/pages.html.erb
<h1><%= t(:pages) %></h1>

<%= render 'menu', :no_edit => true %>

<% if(@pages.length > 0) %>
  <ul>
  <% @pages.each do |page| %>
    <li>
      <%= link_to page, wiki_page_url(:id => page) %>
    </li>
  <% end %>
  </ul>
<% else %>
  <p><%= t(:there_are_no_sub_pages) %></p>
<% end %>

app/views/wiki/revisions.html.erb
<h1><%= t(:revisions) %></h1>

<%= render 'menu', :no_edit => true %>

<% if(@revisions.length > 0) %>
  <ul>
  <% @revisions.each do |revision| %>
    <li>
      <% if (params[:id].nil?) %>
      <% url = edit_wiki_index_url(@project, :revision => revision) %>
    <% else %>
      <% url = edit_wiki_page_url(@project, :revision => revision) %>
    <% end %>
      <%= link_to revision, url %>
      - <%= revision.message %>
      - <%= time_ago_in_words revision.date.to_time %> <%= t(:ago) %>
      - <%= revision.author.name %>
    </li>
  <% end %>
  </ul>
<% else %>
  <p><%= t(:there_are_no_revisions) %></p>
<% end %>

app/views/wiki/show.html.erb
<h1><%= @wiki.id %></h1>

<%= render 'contents' %>

app/views/wiki/structure.html.erb
<h1><%= t(:structure) %></h1>

<%= render 'menu', :no_edit => true %>

<ul>
<% @pages.each do |page| %>
  <li>
    <%= link_to page.id, wiki_page_path(:id => page.id) %>
  </li>
<% end %>
</ul>