config/routes.rb
Ape::Application.routes.draw do
  resources :projects

  # Comments
  match '/projects/:project_id/:type/comments/:id/edit(.:format)' => 'comments#edit', :as => 'edit_index_comment', :via => 'get'
  match '/projects/:project_id/:type/comments(.:format)' => 'comments#create', :as => 'index_comments', :via => 'post'
  match '/projects/:project_id/:type/comments/:id(.:format)' => 'comments#update', :as => 'index_comment', :via => 'put'
  match '/projects/:project_id/:type/comments/:id(.:format)' => 'comments#destroy', :as => 'index_comment', :via => 'delete'

  match '/projects/:project_id/:type/*type_id/comments/:id/edit(.:format)' => 'comments#edit', :as => 'edit_comment', :via => 'get'
  match '/projects/:project_id/:type/*type_id/comments(.:format)' => 'comments#create', :as => 'comments', :via => 'post'
  match '/projects/:project_id/:type/*type_id/comments/:id(.:format)' => 'comments#update', :as => 'comment', :via => 'put'
  match '/projects/:project_id/:type/*type_id/comments/:id(.:format)' => 'comments#destroy', :as => 'comment', :via => 'delete'

  # Wiki index
  match '/projects/:project_id/wiki/structure(.:format)' => 'wiki#structure', :as => 'wiki_structure', :via => 'get'
  match '/projects/:project_id/wiki(.:format)' => 'wiki#index', :as => 'wiki_index', :via => 'get'
  match '/projects/:project_id/wiki/edit(.:format)' => 'wiki#edit', :as => 'edit_wiki_index', :via => 'get'
  match '/projects/:project_id/wiki(.:format)' => 'wiki#update', :as => 'wiki_index', :via => 'put'
  match '/projects/:project_id/wiki/new(.:format)' => 'wiki#new', :as => 'new_wiki_index_page', :via => 'get'
  match '/projects/:project_id/wiki(.:format)' => 'wiki#create', :as => 'wiki_index_page', :via => 'post'
  match '/projects/:project_id/wiki/pages(.:format)' => 'wiki#pages', :as => 'wiki_index_pages', :via => 'get'
  match '/projects/:project_id/wiki/revisions(.:format)' => 'wiki#revisions', :as => 'wiki_index_revisions', :via => 'get'

  # Wiki pages
  match '/projects/:project_id/wiki/*id/pages(.:format)' => 'wiki#pages', :as => 'wiki_pages', :via => 'get'
  match '/projects/:project_id/wiki/*id/revisions(.:format)' => 'wiki#revisions', :as => 'wiki_page_revisions', :via => 'get'
  match '/projects/:project_id/wiki/*id/new(.:format)' => 'wiki#new', :as => 'new_wiki_page', :via => 'get'
  match '/projects/:project_id/wiki/*id/edit(.:format)' => 'wiki#edit', :as => 'edit_wiki_page', :via => 'get'
  match '/projects/:project_id/wiki/*id(.:format)' => 'wiki#show', :as => 'wiki_page', :via => 'get'
  match '/projects/:project_id/wiki/*id(.:format)' => 'wiki#create', :as => 'wiki_page', :via => 'post'
  match '/projects/:project_id/wiki/*id(.:format)' => 'wiki#update', :as => 'wiki_page', :via => 'put'
  match '/projects/:project_id/wiki/*id(.:format)' => 'wiki#destroy', :as => 'wiki_page', :via => 'delete'

  # Tickets
  match '/projects/:project_id/tickets(.:format)' => 'tickets#index', :as => 'tickets', :via => 'get'
  match '/projects/:project_id/tickets(.:format)' => 'tickets#create', :as => 'tickets', :via => 'post'
  match '/projects/:project_id/tickets/*id(.:format)' => 'tickets#create', :as => 'create_sub_ticket', :via => 'post'
  match '/projects/:project_id/tickets/new(.:format)' => 'tickets#new', :as => 'new_ticket', :via => 'get'
  match '/projects/:project_id/tickets/*id/new(.:format)' => 'tickets#new', :as => 'new_sub_ticket', :via => 'get'
  match '/projects/:project_id/tickets/*id/edit(.:format)' => 'tickets#edit', :as => 'edit_ticket', :via => 'get'
  match '/projects/:project_id/tickets/*id(.:format)' => 'tickets#show', :as => 'ticket', :via => 'get'
  match '/projects/:project_id/tickets/*id(.:format)' => 'tickets#update', :as => 'ticket', :via => 'put'
  match '/projects/:project_id/tickets/*id(.:format)' => 'tickets#destroy', :as => 'ticket', :via => 'delete'

  root :to => 'projects#index'
end

app/models/ticket.rb
class Ticket < Versionable
  def initialize(hash)
    super hash.merge(:type_identifier => 'tickets')
  end

  def self.type_identifier
    'tickets'
  end

  def self.all(hash)
    super hash.merge(:type_identifier => self.type_identifier)
  end

  def self.find(hash)
    super hash.merge(:type_identifier => self.type_identifier)
  end

  def self.roots(hash)
    raise ArgumentError unless hash.has_key?(:project)

    items = []

    git_repository = Git.open hash[:project].directory

    Dir.chdir File.join hash[:project].directory, self.type_identifier
    children = Dir['*/'].map do |dir|
      filename = File.join hash[:project].directory, self.type_identifier, dir, 'index.txt'
      contents = read_file(filename)
      author = git_repository.log.path(filename).first.author

      hash = {
        :project => hash[:project],
        :id => dir,
        :name => author.name,
        :email => author.email,
        :date => author.date,
        :contents => contents,
        :type_identifier => self.type_identifier
      }

      items << Ticket.new(hash) unless contents.empty?
    end

    items.sort
  end

  def <=>(o)
    name_cmp = @id <=> o.id
    return name_cmp
  end

  def open?
    status == 'Open'
  end

  def closed?
    !open?
  end

  def status
    load_config
    @config['status']
  end

  def config_file
    File.join directory, 'config.yml'
  end

  def save_config
    unless @config.nil?
      file = File.new config_file, 'w'
      file.puts YAML.dump @config
      file.close

      @project.commit_all 'Update config'
    end
  end

  def save!(message)
    super message

    create_config_file
    save_config
  end

  private
    def create_config_file
      unless File.exists? config_file
        @config = {}
        @config['status'] = 'Open'
      end
      save_config
    end

    def load_config
      file = File.new config_file, 'r'
      @config = YAML.load file.read
      file.close
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_filter :get_project

  def index
    @tickets = Ticket.roots({:project => @project})
  end

  def show
    @ticket = Ticket.find({:project => @project, :id => params[:id]})
  end

  def new
    @ticket = Ticket.new({:project => @project})
  end

  def create
    ticket = Ticket.new({:project => @project, :id => File.join(params[:id].to_s, params[:name]), :contents => params[:content]})

    message = params[:commit_message]
    if message.empty?
      message = 'Add ticket: ' + params[:name]
    end

    ticket.save! message

    redirect_to ticket_url :id => ticket.id
  end

  def edit
    @ticket = Ticket.find({:project => @project, :id => params[:id]})
  end

  def update
    ticket = Ticket.find({:project => @project, :id => params[:id]})

    message = params[:commit_message]
    if message.empty?
      message = 'Update ticket: ' + ticket.id
    end

    ticket.contents = params[:content]

    ticket.save! message

    redirect_to ticket_url :id => ticket.id
  end

  def destroy
    ticket = Ticket.find({:project => @project, :id => params[:id]})

    message = params[:commit_message].to_s
    if message.empty?
      message = 'Delete ticket: ' + ticket.id
    end

    ticket.destroy! message

    redirect_to tickets_url
  end

  private
    def get_project
      @project = Project.find_by_slug params[:project_id]
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_menu.html.erb
<%= link_to t(:new_ticket), new_ticket_path %>

<hr />

app/views/tickets/edit.html.erb
<h1><%= t :edit_ticket %></h1>

<%= form_tag ticket_url(:id => @ticket.id), {:method => :put} do |f| %>
  <div id="ticket-form">
    <ul>
      <li>
        <%= label_tag :content %><br />
        <%= text_area_tag :content, @ticket.contents %>
      </li>
      <li>
        <%= label_tag :commit_message %><br />
        <%= text_field_tag :commit_message %>
      </li>
      <li>
        <%= submit_tag t(:save) %> <%= link_to t(:cancel), ticket_url(:id => @ticket.id) %>
      </li>
    </ul>
  </div>
<% end %>

app/views/tickets/index.html.erb
<h1><%= t(:tickets) %></h1>

<%= render :partial => 'menu' %>

<ul>
<% @tickets.each do |ticket| %>
  <li>
    <%= link_to ticket.id, ticket_path(:id => ticket.id) %>
  </li>
<% end %>
</ul>

app/views/tickets/new.html.erb
<h1><%= t :new_ticket %></h1>

<% if (params[:id].nil?) %>
  <% url = tickets_url %>
<% else %>
  <% url = create_sub_ticket_url %>
<% end %>

<%= form_tag url do |f| %>
  <div id="ticket-form">
    <ul>
      <li>
        <%= label_tag :name %><br />
        <%= text_field_tag :name %>
      </li>
      <li>
        <%= label_tag :content %><br />
        <%= text_area_tag :content %>
      </li>
      <li>
        <%= label_tag :commit_message %><br />
        <%= text_field_tag :commit_message %>
      </li>
      <li>
        <%= submit_tag t(:save) %> | <%= link_to t(:cancel), tickets_url %>
      </li>
    </ul>
  </div>
<% end %>

app/views/tickets/show.html.erb
<%= link_to t(:edit), edit_ticket_url %>
<%= button_to t(:delete), ticket_path, :method => :delete, :confirm => t(:are_you_sure) %>

<p>
  <%= gravatar_for @ticket %> - <%= time_ago_in_words @ticket.date.to_time %> <%= t(:ago) %>
</p>

<p><%= t(:status) %>: <%= @ticket.status %></p>

<%= rewrite_wiki_links @ticket %>